#!/bin/sh
DIR=${HOME}/00INFOBASE/09LOGS
DATE=`date "+%Y-%m-%d"`
TIME=`date "+%H:%M"`
NAME="daily-journal.txt"
FILENAME=$DIR/$DATE-$NAME

if [ ! -d "${DIR}" ]; then
    mkdir -p "${DIR}"
fi

entry=$(cat)
echo "### $TIME" >> $FILENAME && \
echo "" >> $FILENAME && \
echo "$entry" >> $FILENAME && \
echo "" >> $FILENAME
