import = ["~/.config/alacritty/alacritty-theme.toml", "~/.local/share/alacritty/site.toml"]

[cursor]
blink_timeout = 0
vi_mode_style = "Beam"

[cursor.style]
blinking = "Always"
shape = "Beam"

[env]
TERM = "xterm-256color"

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[selection]
save_to_clipboard = true

[window]
decorations = "none"
startup_mode = "Maximized"
